platform: linux


image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: git-assets
- name: version
- name: pre-release

outputs:
- name: volume-demo-releases

run:
  path: git-assets/ci/tasks/release.sh
